export const initDatosAdicionales = {
  campoUno: {
    nomDatoAdicional: 'campoUno',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoDos: {
    nomDatoAdicional: 'campoDos',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoTres: {
    nomDatoAdicional: 'campoTres',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoCuatro: {
    nomDatoAdicional: 'campoCuatro',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoCinco: {
    nomDatoAdicional: 'campoCinco',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoSeis: {
    nomDatoAdicional: 'campoSeis',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoSiete: {
    nomDatoAdicional: 'campoSiete',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoOcho: {
    nomDatoAdicional: 'campoOcho',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoNueve: {
    nomDatoAdicional: 'campoNueve',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoDiez: {
    nomDatoAdicional: 'campoDiez',
    nomTipoDato: 'dxTextBox',
    requerido: false,
    visible: false,
    value: '',
  },
  campoOnce: {
    nomDatoAdicional: 'campoOnce',
    nomTipoDato: 'dxSelectBox',
    requerido: false,
    visible: false,
    value: '',
    data: [],
  },
  campoDoce: {
    nomDatoAdicional: 'campoDoce',
    nomTipoDato: 'dxSelectBox',
    requerido: false,
    visible: false,
    value: '',
    data: [],
  },
  campoTrece: {
    nomDatoAdicional: 'campoTrece',
    nomTipoDato: 'dxSelectBox',
    requerido: false,
    visible: false,
    value: '',
    data: [],
  },
  campoCatorce: {
    nomDatoAdicional: 'campoCatorce',
    nomTipoDato: 'dxSelectBox',
    requerido: false,
    visible: false,
    value: '',
    data: [],
  },
  campoQuince: {
    nomDatoAdicional: 'campoQuince',
    nomTipoDato: 'dxSelectBox',
    requerido: false,
    visible: false,
    value: '',
    data: [],
  },
};
